server:
  port: 5001

jwt:
  secret: Key#SuperSecret$Aforo2SS#JavaMicroservices#987654321

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: security
          uri: http://localhost:80
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1
        - id: invoice
          uri: http://localhost:82
          predicates:
            - Path=/invoice/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: pay
          uri: http://localhost:81
          predicates:
            - Path=/pay/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: transaction
          uri: http://localhost:83
          predicates:
            - Path=/transaction/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
